### ISSUE TITLE
Update to dio 4.0.0

### ISSUE THREAD

**Issue by ivatar39** [TarekkMA/gql_dio_link#6]
So I've installed your package, and, unfortunately, it does not support latest dio release.

`Because every version of gql_dio_link depends on dio ^3.0.9 and mocsi_client depends on dio ^4.0.0, gql_dio_link is forbidden.
So, because mocsi_client depends on gql_dio_link ^0.0.4, version solving failed.
pub get failed (1; So, because mocsi_client depends on gql_dio_link ^0.0.4, version solving failed.)`

**Comment by TarekkMA** [comment]
Can you reopen this issue here, https://github.com/gql-dart/gql with [gql_dio_link] in the title
